





           ECON. MARIO OTINIANO ROMERO

                                  OFICINA REGIONAL DE PLANIF. Y PPTO.
                               
                               
                               
                               
                               
                               
                               
                               
                               
                               
                               
                               
                               
                               
                               
                               




			  			    SERVICIOS NO PERSONALES POR LA REFORMULACION

          DEL SISTEMA INTEGRAL DE ADMINISTRACION   Y PRESUPUESTO   SEGUN 
      	  MEMORANDUN N§ 136-97/CTAR-RG-ST DEL 23.04.97
      
      
      
      
      
      
      
      
      
      
    



      
                  DIGITADORA MILUSKA ATARAMA RODRIGUEZ
      
                  URB. PIURA 2DA. ETAPA E4 - 5 - PIURA
      
                  02792425
                  
                  
                  

	      900.00                