*** 
*** ReFox X  #UK933629  MANRIQUE ORELLANA  MANSOFT SYSTEMS [FP25]
***
SET PRINTER ON
SET DEVICE TO PRINTER
FOR a = 1 TO 50
     @ a, 01 SAY a
ENDFOR
EJECT
SET PRINTER TO
SET PRINTER OFF
SET DEVICE TO SCREEN
*
*** 
*** ReFox - retrace your steps ... 
***
