*** 
*** ReFox X  #UK933629  MANRIQUE ORELLANA  MANSOFT SYSTEMS [FP25]
***
SET PRINTER ON
SET DEVICE TO PRINTER
SET PRINTER TO PRINTER_BOLETA
SET CONSOLE OFF
@ PROW(), PCOL() SAY CHR(27) +  ;
  CHR(67) + CHR(33)
FOR a = 1 TO 10
     ? a
ENDFOR
EJECT
SET PRINTER OFF
SET DEVICE TO SCREEN
SET PRINTER TO
SET CONSOLE ON
*
*** 
*** ReFox - retrace your steps ... 
***
