*** 
*** ReFox X  #UK933629  MANRIQUE ORELLANA  MANSOFT SYSTEMS [FP25]
***
SET CONSOLE OFF
SET PRINTER ON
SET DEVICE TO PRINTER
WAIT WINDOW 'PAUSA'
SET PRINTER TO \\SPOOLER
@ 01, 10 SAY 'LINEA NUMERO'
@ 02, 10 SAY 'LINEA NUMERO'
@ 03, 10 SAY 'LINEA NUMERO'
@ 04, 10 SAY 'LINEA NUMERO'
@ 05, 10 SAY 'LINEA NUMERO'
@ 06, 10 SAY 'LINEA NUMERO'
SET PRINTER TO
SET PRINTER OFF
SET DEVICE TO SCREEN
SET CONSOLE ON
*
*** 
*** ReFox - retrace your steps ... 
***
